ci: bump `actions/cache` to v4.2.3
```
Error: Missing download info for actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a
```

Apparently, something broke with v4.1.2, despite the commit SHA being correct...

https://github.com/actions/cache/commit/6849a6489940f00c2f30c0fb92c6274307ccb58a